# Teorema do Limite Central
* **Médias Amostrais**: médias geradas de amostras, geralmente com o propósito de gerar probabilidades
* A média de médias amostrais deve ser mais próxima da média da população com um desvio padrão pequeno
* Quanto maior a quantidade de amostras e médias amostrais utilizadas, mais próximo estará da média geral da População e menor o desvio padrão

<center><h2>Exemplo: Cubo</h2>
Consideremos um dado de seis lados. A probabilidade de dar qualquer valor entre 1 e 6 é de ${\frac {1}{6}}$ ou seja, todos os valores são igualmente possíveis de ocorrer. O conjunto de números possíveis são $[1,2,3,4,5,6]$. Ao realizar a média desse conjunto $(1+2+3+4+5+6)/6$, obtivemos <strong>3.5</strong>.
<img src="imagens/dado.jpg" alt="Dado" width=300px />
</center>

### Importar numpy e matplotlib

In [1]:
import numpy as np
import matplotlib.pyplot as plt

### Média

In [2]:
np.mean([1,2,3,4,5,6])

3.5

### Jogar dado aleatoriamente

In [5]:
np.random.randint(1,7)

3

### Jogar dado aleatoriamente 6 vezes

In [9]:
np.random.randint(1,7,6)

array([1, 3, 2, 3, 1, 3])

### Gerar os mesmos números aleatórios
Fornecendo um valor como semente _(seed)_ $\Rightarrow$ "123"

In [13]:
np.random.seed(123)
np.random.randint(1,7,6)

array([6, 3, 5, 3, 2, 4])

### Jogar dado aleatoriamente 40 vezes

In [16]:
np.random.seed(123)
amostra = np.random.randint(1,7,40)
amostra

array([6, 3, 5, 3, 2, 4, 3, 4, 2, 2, 1, 2, 2, 1, 1, 2, 4, 6, 5, 1, 1, 5,
       2, 4, 3, 5, 3, 5, 1, 6, 1, 2, 4, 5, 5, 5, 2, 6, 4, 3])

### Gerar média amostral

In [17]:
np.mean(amostra)

3.275

### Utilizar mil médias amostrais
Comprovar o Teorema do Limite Central (TLC)

In [19]:
np.random.seed(123)
medias_amostrais = [np.mean(np.random.randint(1,7,40)) for _ in range(1000)]
medias_amostrais

[3.275,
 3.625,
 3.4,
 3.55,
 3.375,
 3.55,
 3.475,
 3.65,
 3.5,
 3.1,
 3.4,
 3.45,
 3.425,
 3.9,
 3.7,
 3.525,
 3.7,
 3.5,
 3.475,
 3.0,
 3.55,
 3.725,
 3.475,
 3.35,
 3.35,
 3.45,
 3.225,
 3.625,
 3.725,
 3.925,
 3.1,
 3.025,
 3.475,
 3.9,
 3.325,
 3.625,
 3.2,
 3.7,
 3.55,
 3.4,
 3.55,
 3.575,
 3.275,
 3.65,
 3.525,
 3.675,
 3.65,
 3.975,
 3.075,
 3.325,
 3.875,
 3.575,
 3.5,
 3.9,
 3.4,
 3.5,
 3.45,
 3.375,
 3.325,
 3.35,
 3.35,
 3.3,
 3.15,
 3.05,
 3.975,
 3.375,
 3.625,
 3.35,
 3.4,
 3.35,
 4.175,
 3.325,
 3.775,
 3.175,
 3.3,
 3.225,
 3.325,
 3.425,
 3.4,
 3.2,
 3.65,
 3.6,
 3.325,
 4.3,
 3.35,
 3.175,
 3.45,
 3.75,
 3.625,
 2.925,
 3.0,
 3.775,
 3.2,
 3.65,
 2.95,
 3.25,
 3.3,
 3.275,
 3.325,
 4.025,
 3.275,
 3.45,
 2.975,
 3.65,
 3.5,
 3.15,
 3.725,
 3.85,
 3.625,
 3.525,
 3.625,
 3.325,
 3.75,
 3.875,
 3.525,
 3.625,
 4.05,
 3.225,
 3.575,
 3.675,
 3.5,
 3.075,
 3.0,
 3.825,
 3.475,
 3.475,
 3.575,
 3.325,
 3.55,
 3.3,
 3.4,
 3.425,
 3.15,
 3.55,
 3.55,
 3.45,
 3.7,
 3.8,
 3.

### Média

### Mediana

### Moda

# Teorema do Limite Central em um DataFrame
Aplicando o mesmo conceito com um DataFrame de um arquivo CSV

### Importar pandas

### Ler DataFrame do arquivo 'weight-height.csv'

### Verificar tamanho da amostra

### Gerar amostra aleatória 5 elementos

### Gerar 200 médias amostrais de 50 amostras cada